services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app:cached
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: "8000"
    restart: on-failure      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
